"""Curated dataset of high-impact historical, CTF, and pentesting CVEs for instant offline study and usage."""

COMMON_CVES = [
    # =========================================================================
    # CLASSIC & ESSENTIAL CTF / NETWORK SERVICES
    # =========================================================================
    {
        "cve_id": "CVE-2011-2523",
        "state": "PUBLISHED",
        "assigner": "vsftpd",
        "date_published": "2011-07-03",
        "year": 2011,
        "title": "vsftpd 2.3.4 Smiley Backdoor Remote Code Execution",
        "description": "vsftpd 2.3.4 contains a backdoor in its source code distribution. When a username containing a smiley face ':) ' is sent during login, the daemon opens a root bind shell on TCP port 6200 without requiring valid credentials.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 10.0,
        "cwe_ids": "CWE-506",
        "vuln_types": "rce, auth-bypass",
        "affected_vendors": "vsftpd",
        "affected_products": "vsftpd",
        "affected_versions": "2.3.4",
        "references_json": '["https://scarybeastsecurity.blogspot.com/2011/07/alert-vsftpd-download-backdoored.html"]',
        "raw_json": '[{"vendor": "vsftpd", "product": "vsftpd", "version": "2.3.4"}]'
    },
    {
        "cve_id": "CVE-2015-3306",
        "state": "PUBLISHED",
        "assigner": "ProFTPD",
        "date_published": "2015-05-18",
        "year": 2015,
        "title": "ProFTPD 1.3.5 mod_copy Unauthenticated Arbitrary File Copy to RCE",
        "description": "The mod_copy module in ProFTPD 1.3.5 allows unauthenticated remote attackers to execute arbitrary SITE CPFR (copy from) and SITE CPTO (copy to) commands before authentication, enabling unauthorized reading and copying of any file (e.g. PHP shells into web roots).",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 7.5,
        "cwe_ids": "CWE-284, CWE-22",
        "vuln_types": "auth-bypass, lfi, rce",
        "affected_vendors": "ProFTPD Project",
        "affected_products": "ProFTPD",
        "affected_versions": "1.3.5",
        "references_json": '["https://bugs.proftpd.org/show_bug.cgi?id=4169", "https://www.exploit-db.com/exploits/36742"]',
        "raw_json": '[{"vendor": "ProFTPD", "product": "ProFTPD", "version": "1.3.5"}]'
    },
    {
        "cve_id": "CVE-2010-2075",
        "state": "PUBLISHED",
        "assigner": "UnrealIRCd",
        "date_published": "2010-06-16",
        "year": 2010,
        "title": "UnrealIRCd 3.2.8.1 Malicious Backdoor Remote Code Execution",
        "description": "UnrealIRCd 3.2.8.1 download archives were modified to contain a Trojan horse backdoor. Sending any command starting with 'AB;' followed by shell commands executes arbitrary code with privileges of the IRCd process.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 7.5,
        "cwe_ids": "CWE-506",
        "vuln_types": "rce",
        "affected_vendors": "UnrealIRCd",
        "affected_products": "UnrealIRCd",
        "affected_versions": "3.2.8.1",
        "references_json": '["https://www.unrealircd.org/txt/unrealsecadvisory.20100612.txt"]',
        "raw_json": '[{"vendor": "UnrealIRCd", "product": "UnrealIRCd", "version": "3.2.8.1"}]'
    },
    {
        "cve_id": "CVE-2004-2687",
        "state": "PUBLISHED",
        "assigner": "distcc",
        "date_published": "2004-12-31",
        "year": 2004,
        "title": "distcc Daemon Unauthenticated Remote Code Execution",
        "description": "distcc 2.x before 2.18.2 allows remote attackers to execute arbitrary commands on the compilation daemon server via crafted DISTCC_CMD arguments without authentication.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 7.5,
        "cwe_ids": "CWE-94",
        "vuln_types": "rce, auth-bypass",
        "affected_vendors": "distcc",
        "affected_products": "distcc",
        "affected_versions": "< 2.18.2",
        "references_json": '["https://nvd.nist.gov/vuln/detail/CVE-2004-2687"]',
        "raw_json": '[{"vendor": "distcc", "product": "distcc", "version": "<2.18.2"}]'
    },
    {
        "cve_id": "CVE-2007-2447",
        "state": "PUBLISHED",
        "assigner": "Samba",
        "date_published": "2007-05-14",
        "year": 2007,
        "title": "Samba 3.0.0 - 3.0.25rc3 usermap script Remote Command Execution",
        "description": "The MS-RPC functionality in smbd in Samba 3.0.0 through 3.0.25rc3 allows remote attackers to execute arbitrary shell commands via shell metacharacters in the username parameter when the 'username map script' option is enabled in smb.conf.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 6.0,
        "cwe_ids": "CWE-78",
        "vuln_types": "rce",
        "affected_vendors": "Samba",
        "affected_products": "Samba",
        "affected_versions": "3.0.0 <= 3.0.25rc3",
        "references_json": '["https://www.samba.org/samba/security/CVE-2007-2447.html"]',
        "raw_json": '[{"vendor": "Samba", "product": "Samba", "version": "3.0.0..3.0.25rc3"}]'
    },
    {
        "cve_id": "CVE-2017-7494",
        "state": "PUBLISHED",
        "assigner": "Samba",
        "date_published": "2017-05-24",
        "year": 2017,
        "title": "Samba Remote Code Execution (SambaCry / EternalRed)",
        "description": "All versions of Samba from 3.5.0 onwards allow remote authenticated users to upload a shared library to a writable share and cause the server to load and execute it with root privileges via pipe name parsing.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 10.0,
        "cwe_ids": "CWE-94",
        "vuln_types": "rce",
        "affected_vendors": "Samba",
        "affected_products": "Samba",
        "affected_versions": "3.5.0 <= 4.6.4",
        "references_json": '["https://www.samba.org/samba/security/CVE-2017-7494.html"]',
        "raw_json": '[{"vendor": "Samba", "product": "Samba", "version": "3.5.0..4.6.4"}]'
    },

    # =========================================================================
    # WEB APPLICATION FRAMEWORKS & SERVERS
    # =========================================================================
    {
        "cve_id": "CVE-2021-44228",
        "state": "PUBLISHED",
        "assigner": "Apache",
        "date_published": "2021-12-10",
        "year": 2021,
        "title": "Apache Log4j2 JNDI Remote Code Execution (Log4Shell)",
        "description": "Apache Log4j2 2.0-beta9 through 2.15.0 JNDI features do not protect against attacker-controlled LDAP/RMI endpoints. An attacker controlling log messages (e.g. User-Agent: ${jndi:ldap://...}) executes arbitrary Java code with application privileges.",
        "cvss_v3_score": 10.0,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cvss_v2_score": 9.3,
        "cwe_ids": "CWE-502, CWE-400, CWE-20",
        "vuln_types": "rce",
        "affected_vendors": "Apache Software Foundation",
        "affected_products": "Apache Log4j",
        "affected_versions": "2.0-beta9 <= 2.14.1",
        "references_json": '["https://logging.apache.org/log4j/2.x/security.html"]',
        "raw_json": '[{"vendor": "Apache", "product": "Log4j", "version": "2.0-beta9..2.14.1"}]'
    },
    {
        "cve_id": "CVE-2021-41773",
        "state": "PUBLISHED",
        "assigner": "Apache",
        "date_published": "2021-10-05",
        "year": 2021,
        "title": "Apache HTTP Server 2.4.49 Path Traversal and RCE",
        "description": "Flaw in path normalization in Apache 2.4.49 allows mapping URLs to files outside document root (via /icons/.%2e/%2e%2e/...) and executing CGI binaries (like /cgi-bin/.%2e/.%2e/bin/sh) for remote code execution.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 7.5,
        "cwe_ids": "CWE-22",
        "vuln_types": "lfi, rce",
        "affected_vendors": "Apache Software Foundation",
        "affected_products": "Apache HTTP Server",
        "affected_versions": "2.4.49",
        "references_json": '["https://httpd.apache.org/security/vulnerabilities_24.html"]',
        "raw_json": '[{"vendor": "Apache", "product": "HTTP Server", "version": "2.4.49"}]'
    },
    {
        "cve_id": "CVE-2021-42013",
        "state": "PUBLISHED",
        "assigner": "Apache",
        "date_published": "2021-10-07",
        "year": 2021,
        "title": "Apache HTTP Server 2.4.49 and 2.4.50 Incomplete Path Traversal Fix RCE",
        "description": "Fix for CVE-2021-41773 in Apache 2.4.50 was incomplete. Using double URL-encoding (%%32%65%%32%65) allows directory traversal and remote code execution if mod_cgi is enabled.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-22",
        "vuln_types": "lfi, rce",
        "affected_vendors": "Apache Software Foundation",
        "affected_products": "Apache HTTP Server",
        "affected_versions": "2.4.49, 2.4.50",
        "references_json": '["https://httpd.apache.org/security/vulnerabilities_24.html"]',
        "raw_json": '[{"vendor": "Apache", "product": "HTTP Server", "version": "2.4.49..2.4.50"}]'
    },
    {
        "cve_id": "CVE-2020-1938",
        "state": "PUBLISHED",
        "assigner": "Apache",
        "date_published": "2020-02-24",
        "year": 2020,
        "title": "Apache Tomcat AJP File Read / Inclusion and RCE (Ghostcat)",
        "description": "Apache Tomcat AJP connector (port 8009) is enabled by default with all IP addresses bound. When exploiting this flaw, attackers can read webapp files including WEB-INF/web.xml or include uploaded files as JSP for remote code execution.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 7.5,
        "cwe_ids": "CWE-200, CWE-22",
        "vuln_types": "lfi, rce, info-leak",
        "affected_vendors": "Apache Software Foundation",
        "affected_products": "Apache Tomcat",
        "affected_versions": "6.x, 7.0.0 <= 7.0.99, 8.5.0 <= 8.5.50, 9.0.0.M1 <= 9.0.30",
        "references_json": '["https://www.chaitin.cn/en/ghostcat"]',
        "raw_json": '[{"vendor": "Apache", "product": "Tomcat", "version": "6..9.0.30"}]'
    },
    {
        "cve_id": "CVE-2017-12615",
        "state": "PUBLISHED",
        "assigner": "Apache",
        "date_published": "2017-09-19",
        "year": 2017,
        "title": "Apache Tomcat PUT Method Arbitrary File Upload JSP RCE",
        "description": "When running on Windows with readonly=false in DefaultServlet, attackers can upload arbitrary JSP scripts via crafted HTTP PUT requests (e.g. PUT /shell.jsp/ or PUT /shell.jsp::$DATA) resulting in remote code execution.",
        "cvss_v3_score": 8.1,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-434",
        "vuln_types": "rce, lfi",
        "affected_vendors": "Apache Software Foundation",
        "affected_products": "Apache Tomcat",
        "affected_versions": "7.0.0 <= 7.0.79",
        "references_json": '["https://lists.apache.org/thread.html/rda45ccaa1b2a95c962b1a8d3e23924dbb9b47e279260d71b869cc9cf%40%3Cdev.tomcat.apache.org%3E"]',
        "raw_json": '[{"vendor": "Apache", "product": "Tomcat", "version": "7.0.0..7.0.79"}]'
    },
    {
        "cve_id": "CVE-2017-5638",
        "state": "PUBLISHED",
        "assigner": "Apache",
        "date_published": "2017-03-11",
        "year": 2017,
        "title": "Apache Struts 2 Jakarta Multipart OGNL Remote Code Execution (S2-045)",
        "description": "The Jakarta Multipart parser in Apache Struts 2.3.5 through 2.3.31 and 2.5 through 2.5.10 mishandles Content-Type headers, allowing remote attackers to execute arbitrary OGNL expressions and shell commands with root/SYSTEM privileges.",
        "cvss_v3_score": 10.0,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cvss_v2_score": 10.0,
        "cwe_ids": "CWE-917, CWE-94",
        "vuln_types": "rce",
        "affected_vendors": "Apache Software Foundation",
        "affected_products": "Apache Struts",
        "affected_versions": "2.3.5 <= 2.3.31, 2.5 <= 2.5.10",
        "references_json": '["https://cwiki.apache.org/confluence/display/WW/S2-045"]',
        "raw_json": '[{"vendor": "Apache", "product": "Struts", "version": "2.3.5..2.5.10"}]'
    },
    {
        "cve_id": "CVE-2018-7600",
        "state": "PUBLISHED",
        "assigner": "Drupal",
        "date_published": "2018-03-29",
        "year": 2018,
        "title": "Drupal Form API AJAX Render Array Remote Code Execution (Drupalgeddon 2)",
        "description": "Drupal 7.x before 7.58, 8.x before 8.3.9, 8.4.x before 8.4.6, and 8.5.x before 8.5.1 does not properly sanitize Form API input, allowing unauthenticated attackers to pass render arrays (#lazy_builder, #post_render) via AJAX requests to execute arbitrary system commands.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 7.5,
        "cwe_ids": "CWE-20",
        "vuln_types": "rce, auth-bypass",
        "affected_vendors": "Drupal",
        "affected_products": "Drupal Core",
        "affected_versions": "7.x < 7.58, 8.x < 8.5.1",
        "references_json": '["https://www.drupal.org/sa-core-2018-002"]',
        "raw_json": '[{"vendor": "Drupal", "product": "Drupal", "version": "7.x..8.5.1"}]'
    },
    {
        "cve_id": "CVE-2019-15107",
        "state": "PUBLISHED",
        "assigner": "Webmin",
        "date_published": "2019-08-27",
        "year": 2019,
        "title": "Webmin password_change.cgi Unauthenticated Remote Code Execution",
        "description": "password_change.cgi in Webmin 1.890 through 1.920 contains a backdoor parameter flaw. When password expiration is enabled, an unauthenticated attacker can supply pipe characters in the 'user' parameter (e.g. user=root|id) to execute arbitrary commands as root.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-78",
        "vuln_types": "rce, auth-bypass",
        "affected_vendors": "Webmin",
        "affected_products": "Webmin",
        "affected_versions": "1.890 <= 1.920",
        "references_json": '["https://www.webmin.com/exploit.html"]',
        "raw_json": '[{"vendor": "Webmin", "product": "Webmin", "version": "1.890..1.920"}]'
    },
    {
        "cve_id": "CVE-2022-0543",
        "state": "PUBLISHED",
        "assigner": "Debian",
        "date_published": "2022-02-18",
        "year": 2022,
        "title": "Redis Debian/Ubuntu Lua Sandbox Escape Remote Code Execution",
        "description": "Due to a packaging bug in Debian/Ubuntu, Redis Lua environment was not completely sanitized and package.loadlib remained accessible. Unauthenticated attackers can load shared libraries or run os.execute via EVAL commands (e.g. EVAL 'local io_l = package.loadlib(\"/usr/lib/x86_64-linux-gnu/liblua5.1.so.0\", \"luaopen_io\"); local io = io_l(); local f = io.popen(\"id\", \"r\"); local res = f:read(\"*a\"); f:close(); return res' 0).",
        "cvss_v3_score": 10.0,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_ids": "CWE-269",
        "vuln_types": "rce, privesc",
        "affected_vendors": "Debian, Ubuntu",
        "affected_products": "Redis",
        "affected_versions": "5:5.0.3-4+deb10u3, 5:6.0.16-1+deb11u1",
        "references_json": '["https://www.ubercomp.com/posts/2022-01-20_redis_on_debian_rce"]',
        "raw_json": '[{"vendor": "Redis", "product": "Redis", "version": "5.0..6.0"}]'
    },

    # =========================================================================
    # LINUX KERNEL & LOCAL PRIVILEGE ESCALATION (LPE)
    # =========================================================================
    {
        "cve_id": "CVE-2022-0847",
        "state": "PUBLISHED",
        "assigner": "Linux Kernel",
        "date_published": "2022-03-10",
        "year": 2022,
        "title": "Linux Kernel Arbitrary Read-Only File Overwrite LPE (Dirty Pipe)",
        "description": "Flaw in the pipe buffer flags handling in Linux kernel 5.8 through 5.16.11 allows unprivileged local users to write to arbitrary read-only page cache pages, enabling immediate root escalation by overwriting /etc/passwd or SUID binaries.",
        "cvss_v3_score": 7.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-269, CWE-732",
        "vuln_types": "privesc",
        "affected_vendors": "Linux",
        "affected_products": "Linux Kernel",
        "affected_versions": "5.8 <= 5.16.11",
        "references_json": '["https://dirtypipe.cm4all.com/"]',
        "raw_json": '[{"vendor": "Linux", "product": "Kernel", "version": "5.8..5.16.11"}]'
    },
    {
        "cve_id": "CVE-2021-4034",
        "state": "PUBLISHED",
        "assigner": "Qualys",
        "date_published": "2022-01-26",
        "year": 2021,
        "title": "Polkit pkexec Out-of-Bounds Memory Corruption LPE (PwnKit)",
        "description": "pkexec in polkit allows local unprivileged users to execute arbitrary code as root by passing an empty argc argument list (argc=0) to trigger an out-of-bounds environment variable injection.",
        "cvss_v3_score": 7.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-787, CWE-125",
        "vuln_types": "privesc, memory-corruption",
        "affected_vendors": "Polkit",
        "affected_products": "pkexec",
        "affected_versions": "All versions since 2009",
        "references_json": '["https://www.qualys.com/2022/01/25/cve-2021-4034/pwnkit.txt"]',
        "raw_json": '[{"vendor": "Polkit", "product": "pkexec", "version": "all"}]'
    },
    {
        "cve_id": "CVE-2021-3156",
        "state": "PUBLISHED",
        "assigner": "Qualys",
        "date_published": "2021-01-26",
        "year": 2021,
        "title": "Sudo Heap-Based Buffer Overflow (Baron Samedit)",
        "description": "Off-by-one heap overflow in sudo parse_args() allows unprivileged users to escalate to root via 'sudoedit -s' without requiring sudoers permissions.",
        "cvss_v3_score": 7.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-122, CWE-787, CWE-269",
        "vuln_types": "privesc, memory-corruption",
        "affected_vendors": "Todd C. Miller",
        "affected_products": "Sudo",
        "affected_versions": "1.8.2 <= 1.8.31p2, 1.9.0 <= 1.9.5p1",
        "references_json": '["https://www.qualys.com/2021/01/26/cve-2021-3156/baron-samedit-heap-based-overflow-sudo.txt"]',
        "raw_json": '[{"vendor": "Sudo", "product": "Sudo", "version": "1.8.2..1.9.5p1"}]'
    },
    {
        "cve_id": "CVE-2019-14287",
        "state": "PUBLISHED",
        "assigner": "Sudo",
        "date_published": "2019-10-17",
        "year": 2019,
        "title": "Sudo Security Policy User ID -1 Bypass (sudo -u#-1)",
        "description": "In Sudo before 1.8.28, when a user is allowed to run commands as any user except root (e.g. '(ALL, !root) /bin/bash'), specifying user ID -1 or 4294967295 via 'sudo -u#-1 /bin/bash' runs the command as root (UID 0).",
        "cvss_v3_score": 8.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-269",
        "vuln_types": "privesc, auth-bypass",
        "affected_vendors": "Sudo",
        "affected_products": "Sudo",
        "affected_versions": "< 1.8.28",
        "references_json": '["https://www.sudo.ws/alerts/minus_1_uid.html"]',
        "raw_json": '[{"vendor": "Sudo", "product": "Sudo", "version": "<1.8.28"}]'
    },
    {
        "cve_id": "CVE-2016-5195",
        "state": "PUBLISHED",
        "assigner": "Linux Kernel",
        "date_published": "2016-11-10",
        "year": 2016,
        "title": "Linux Kernel Copy-on-Write Memory Subsystem LPE (Dirty COW)",
        "description": "Race condition in copy-on-write breakage of private read-only memory mappings in Linux kernel allows local users to overwrite read-only files (like /etc/passwd or /bin/su) to achieve root privileges.",
        "cvss_v3_score": 7.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-362",
        "vuln_types": "privesc",
        "affected_vendors": "Linux",
        "affected_products": "Linux Kernel",
        "affected_versions": "2.6.22 <= 4.8.3",
        "references_json": '["https://dirtycow.ninja/"]',
        "raw_json": '[{"vendor": "Linux", "product": "Kernel", "version": "2.6.22..4.8.3"}]'
    },
    {
        "cve_id": "CVE-2019-5736",
        "state": "PUBLISHED",
        "assigner": "Docker / runc",
        "date_published": "2019-02-11",
        "year": 2019,
        "title": "runc / Docker Container Breakout to Host Root Execution",
        "description": "runc through 1.0-rc6 allows malicious containers to overwrite the host runc binary via /proc/self/exe, allowing arbitrary code execution as root on the host machine when a new container is attached.",
        "cvss_v3_score": 8.6,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H",
        "cwe_ids": "CWE-269",
        "vuln_types": "privesc, rce",
        "affected_vendors": "Open Containers Initiative",
        "affected_products": "runc, Docker",
        "affected_versions": "<= 1.0-rc6",
        "references_json": '["https://www.openwall.com/lists/oss-security/2019/02/11/2"]',
        "raw_json": '[{"vendor": "Docker", "product": "runc", "version": "<=1.0-rc6"}]'
    },

    # =========================================================================
    # WINDOWS & ACTIVE DIRECTORY EXPLOITS
    # =========================================================================
    {
        "cve_id": "CVE-2017-0144",
        "state": "PUBLISHED",
        "assigner": "Microsoft",
        "date_published": "2017-03-14",
        "year": 2017,
        "title": "Windows SMBv1 Remote Code Execution (EternalBlue / MS17-010)",
        "description": "The SMBv1 server in Microsoft Windows allows remote attackers to execute arbitrary code via crafted SMB request packets, leading to immediate SYSTEM compromise. Exploited by WannaCry, NotPetya, and widely used in CTFs and OSCP.",
        "cvss_v3_score": 8.1,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 9.3,
        "cwe_ids": "CWE-119",
        "vuln_types": "rce, memory-corruption",
        "affected_vendors": "Microsoft",
        "affected_products": "Windows Server, Windows 7, Windows 10, Windows XP",
        "affected_versions": "SMBv1",
        "references_json": '["https://docs.microsoft.com/en-us/security-updates/securitybulletins/2017/ms17-010"]',
        "raw_json": '[{"vendor": "Microsoft", "product": "Windows SMB", "version": "SMBv1"}]'
    },
    {
        "cve_id": "CVE-2008-4250",
        "state": "PUBLISHED",
        "assigner": "Microsoft",
        "date_published": "2008-10-23",
        "year": 2008,
        "title": "Windows Server Service RPC Buffer Overflow (MS08-067 / NetAPI)",
        "description": "The Server service in Windows 2000, XP, and Server 2003 does not properly handle RPC requests with crafted path names, allowing remote unauthenticated attackers to execute arbitrary code with SYSTEM privileges.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 10.0,
        "cwe_ids": "CWE-119",
        "vuln_types": "rce, memory-corruption",
        "affected_vendors": "Microsoft",
        "affected_products": "Windows 2000, Windows XP, Windows Server 2003",
        "affected_versions": "All NetAPI",
        "references_json": '["https://docs.microsoft.com/en-us/security-updates/securitybulletins/2008/ms08-067"]',
        "raw_json": '[{"vendor": "Microsoft", "product": "Windows", "version": "XP..2003"}]'
    },
    {
        "cve_id": "CVE-2020-1472",
        "state": "PUBLISHED",
        "assigner": "Microsoft",
        "date_published": "2020-08-11",
        "year": 2020,
        "title": "Microsoft Netlogon Elevation of Privilege (Zerologon)",
        "description": "Flaw in AES-CFB8 implementation in Netlogon protocol allows unauthenticated attackers with network access to a Domain Controller to forge Netlogon authentication and set the computer account password to empty, achieving instant Domain Admin.",
        "cvss_v3_score": 10.0,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        "cwe_ids": "CWE-306, CWE-287",
        "vuln_types": "auth-bypass, privesc",
        "affected_vendors": "Microsoft",
        "affected_products": "Windows Server",
        "affected_versions": "2008 R2, 2012, 2016, 2019",
        "references_json": '["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2020-1472"]',
        "raw_json": '[{"vendor": "Microsoft", "product": "Windows Server", "version": "2008..2019"}]'
    },
    {
        "cve_id": "CVE-2021-34527",
        "state": "PUBLISHED",
        "assigner": "Microsoft",
        "date_published": "2021-07-02",
        "year": 2021,
        "title": "Windows Print Spooler Remote Code Execution / LPE (PrintNightmare)",
        "description": "Windows Print Spooler service improperly performs privileged file operations in RpcAddPrinterDriverEx, allowing authenticated domain users to load arbitrary malicious DLLs and achieve SYSTEM code execution on Domain Controllers and Windows endpoints.",
        "cvss_v3_score": 8.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-269",
        "vuln_types": "rce, privesc",
        "affected_vendors": "Microsoft",
        "affected_products": "Windows Server, Windows 10, Windows 11",
        "affected_versions": "All Windows versions",
        "references_json": '["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-34527"]',
        "raw_json": '[{"vendor": "Microsoft", "product": "Windows Print Spooler", "version": "all"}]'
    },
    {
        "cve_id": "CVE-2019-0708",
        "state": "PUBLISHED",
        "assigner": "Microsoft",
        "date_published": "2019-05-16",
        "year": 2019,
        "title": "Windows Remote Desktop Protocol Pre-Auth RCE (BlueKeep)",
        "description": "Remote Desktop Services in Windows 7, Server 2008, Server 2003, and XP mishandles connection requests, allowing unauthenticated remote attackers to send specially crafted requests via RDP (port 3389) and execute arbitrary code in kernel mode.",
        "cvss_v3_score": 9.8,
        "cvss_v3_severity": "CRITICAL",
        "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_v2_score": 10.0,
        "cwe_ids": "CWE-416",
        "vuln_types": "rce, memory-corruption",
        "affected_vendors": "Microsoft",
        "affected_products": "Windows 7, Windows Server 2008, Windows XP",
        "affected_versions": "RDP 5.x, 6.x",
        "references_json": '["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2019-0708"]',
        "raw_json": '[{"vendor": "Microsoft", "product": "RDP", "version": "7..2008"}]'
    },
    {
        "cve_id": "CVE-2022-30190",
        "state": "PUBLISHED",
        "assigner": "Microsoft",
        "date_published": "2022-06-01",
        "year": 2022,
        "title": "Microsoft Windows Support Diagnostic Tool RCE (Follina)",
        "description": "A remote code execution vulnerability exists when MSDT is called using the URL protocol from an application such as Microsoft Word. An attacker who successfully exploits this vulnerability can run arbitrary PowerShell code with the privileges of the calling application even if macros are disabled.",
        "cvss_v3_score": 7.8,
        "cvss_v3_severity": "HIGH",
        "cvss_v3_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
        "cwe_ids": "CWE-94",
        "vuln_types": "rce",
        "affected_vendors": "Microsoft",
        "affected_products": "Microsoft Windows, Microsoft Office",
        "affected_versions": "Windows 7, 8.1, 10, 11, Server",
        "references_json": '["https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-30190"]',
        "raw_json": '[{"vendor": "Microsoft", "product": "MSDT", "version": "all"}]'
    }
]
